# Generated by Django 5.0.3 on 2024-03-28 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('idEntrprise', models.AutoField(primary_key=True, serialize=False)),
                ('raison', models.CharField(max_length=40)),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('adressPostal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pdl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdl', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('numTel', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.user'),
        ),
    ]
